### ISSUE TITLE
Column swiping

### ISSUE THREAD

**Issue by jakearchibald** [jakearchibald/tweetdeck-prototype#3]
On mobile we want to do column swiping like the Twitter native app. This *should* be easy in IE because of http://msdn.microsoft.com/en-us/library/ie/hh772726(v=vs.85).aspx. For other browsers we'll have to make smart use of touch events.

In Chrome, we give you the `touchstart` and the first `touchmove`, if neither are `preventDefault`ed the `touchmove`s get throttled, so you need to decide if you're going to handle the sideways swipe/pan by the first `touchmove`.

`touch-action: pan-y` may help on the columns.

**Comment by phuu** [comment]
Removed columns, so worth reassessing if they come back.
