### ISSUE TITLE
Tweet markup & CSS

### ISSUE THREAD

**Issue by jakearchibald** [jakearchibald/tweetdeck-prototype#4]
<img src="https://cloud.githubusercontent.com/assets/93594/3685570/fe85e05e-130c-11e4-8f1d-823ae9730966.png" alt="2014-07-24 08 31 12" width="300" style="max-width:100%;">

Just thief the design the Twitter app uses. Put the interaction elements (fav, retweet etc) in their own element so they can be hidden until we implement.

**Comment by phuu** [comment]
Done!
