### ISSUE TITLE
Build is broken

### ISSUE THREAD

**Issue by phuu** [jakearchibald/tweetdeck-prototype#44]
`sw.js` needs to be built to the root, not `static/...`

**Comment by ahume** [comment]
Works for me. It builds to /build, but the server serves that file at the required URL.

**Comment by phuu** [comment]
But gh-pages isn't running the server so we need to build to the root, which I think is the bug. I fixed it manually earlier, but will stick up a code fix

**Comment by phuu** [comment]
I think it's fixed.
